### ISSUE TITLE
ehVizinho

### ISSUE THREAD

**Issue by brenoso** [oXcase/graph-theory-practical-assignment#7]
Recebe dois vértices u e v como parâmetros e retorna true se os mesmos são vizinhos

**Comment by oXcase** [comment]
Foi implementado uma função em cada estrutura de dados. Caso necessário, reabrir e implementar apenas na classe Grafo

**Comment by oXcase** [comment]
Resolvido no commit `8206aaa76e7978bfd2fc842377c1a1637f567efb`
